# Generated by Django 3.2.4 on 2021-08-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='quantity',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Quantity'),
        ),
    ]
