# Generated by Django 3.2.5 on 2021-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Expires Datetime'),
        ),
    ]
