# Generated by Django 2.2 on 2021-06-06 22:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('draft', 'Draft'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=100, verbose_name='Status')),
                ('name', models.CharField(max_length=14, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('main_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Main Image')),
                ('sku', models.IntegerField(null=True, verbose_name='Sku')),
                ('category_id', models.IntegerField(null=True, verbose_name='Category Id')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'product Category',
            },
        ),
    ]
