# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
POST http://127.0.0.1:8000/cartlists/add/ HTTP/1.1
content-type: application/json
Authorization: fe58d7e46c8f85565a4cce0811255aa1763c41905ee6e2bc4c056bf4d3cd

{
	"product": 1,
	"quantity": 2
}