# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
POST http://127.0.0.1:8000/posts/add/ HTTP/1.1
content-type: application/json
Authorization: f9012321bd1444f92e05c2ff936246786e1186d028ce854c68278bb33ffc

{
	"name": "hayato",
    "body": "test",
	"image": null
}