# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
POST http://127.0.0.1:8000/wishlists/add/ HTTP/1.1
content-type: application/json
Authorization: 20f7e634366d4836d898ec9cc5d94eebbd0ddf4631ff4878f37f13d92514

{
    "product": 128
}