# Generated by Django 3.2.4 on 2021-07-12 19:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=50, verbose_name='Status')),
                ('name', models.CharField(db_index=True, max_length=14, verbose_name='Name')),
                ('description', models.CharField(db_index=True, max_length=1000, verbose_name='Description')),
                ('main_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Main Image')),
                ('sku', models.IntegerField(db_index=True, verbose_name='SKU Number')),
                ('quantity', models.IntegerField(default=0, verbose_name='Inventory Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='Discount Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
