# Generated by Django 3.2.4 on 2021-07-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
