# Generated by Django 3.2.4 on 2021-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210713_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(choices=[('phone', 'Phone'), ('camera', 'Camera'), ('laptop', 'Laptop'), ('pods', 'Pods'), ('watch', 'Watch'), ('play_station', 'Play Station'), ('others', 'Others')], db_index=True, default='others', max_length=14, verbose_name='Category Name'),
        ),
    ]
