# Generated by Django 3.2.4 on 2021-07-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_index=True, max_length=1000, verbose_name='Description'),
        ),
    ]
